ALTER TYPE manifest_type ADD VALUE IF NOT EXISTS 'QUICK';
ALTER TYPE manifest_type ADD VALUE IF NOT EXISTS 'TARGETED';
ALTER TYPE manifest_type ADD VALUE IF NOT EXISTS 'CUSTOM';

ALTER TABLE manifests ALTER COLUMN title DROP NOT NULL;
