ALTER TABLE items ADD COLUMN user_id TEXT NOT NULL;
ALTER TABLE manifests ADD COLUMN user_id TEXT NOT NULL;
ALTER TABLE merchants ADD COLUMN user_id TEXT NOT NULL;
ALTER TABLE receipts ADD COLUMN user_id TEXT;
ALTER TABLE categories ADD COLUMN user_id TEXT NOT NULL;
ALTER TABLE tags ADD COLUMN user_id TEXT NOT NULL;

ALTER TABLE users DROP COLUMN IF EXISTS callsign;