import { Receipt, Item, Manifest, Analytics, UserProfile } from './types';

export const receipts: Receipt[] = [
  {
    id: '093',
    merchant: 'SECTOR_7_WHOLE_FOODS',
    merchantId: 'mrc-001',
    date: '2024.10.14',
    total: 142.20,
    itemCount: 12,
    status: 'OK',
    savings: 8.40,
    linkedManifestId: 'mft-042',
    items: [
      { id: null, itemId: null, name: 'Bananas', qty: '1.4kg', unitPrice: 0.63, total: 0.89, category: 'Produce', tags: ['ORG', 'SALE'] },
      { id: null, itemId: null, name: 'Whole Milk 1gal', qty: '×2', unitPrice: 3.49, total: 6.98, category: 'Dairy', tags: ['ORG'] },
      { id: null, itemId: null, name: 'Sourdough Loaf', qty: '×1', unitPrice: 7.99, total: 7.99, category: 'Pantry', tags: [] },
      { id: null, itemId: null, name: 'Free Range Eggs 12pk', qty: '×1', unitPrice: 4.50, total: 4.50, category: 'Dairy', tags: ['ORG'] },
      { id: null, itemId: null, name: 'Chicken Breast 1lb', qty: '×2', unitPrice: 9.20, total: 18.40, category: 'Protein', tags: [] },
      { id: null, itemId: null, name: 'Greek Yogurt 32oz', qty: '×1', unitPrice: 6.49, total: 6.49, category: 'Dairy', tags: [] },
      { id: null, itemId: null, name: 'Baby Spinach 5oz', qty: '×1', unitPrice: 3.99, total: 3.99, category: 'Produce', tags: ['ORG'] },
      { id: null, itemId: null, name: 'Pasta Spaghetti 1lb', qty: '×3', unitPrice: 1.79, total: 5.37, category: 'Pantry', tags: [] },
      { id: null, itemId: null, name: 'Olive Oil 500ml', qty: '×1', unitPrice: 11.99, total: 11.99, category: 'Pantry', tags: [] },
      { id: null, itemId: null, name: 'Cheddar Cheese 8oz', qty: '×2', unitPrice: 3.50, total: 7.00, category: 'Dairy', tags: ['SALE'] },
      { id: null, itemId: null, name: 'Kombucha 16oz', qty: '×2', unitPrice: 5.49, total: 10.98, category: 'Beverages', tags: ['PRICE_SPIKE'] },
      { id: null, itemId: null, name: 'Laundry Detergent', qty: '×1', unitPrice: 17.62, total: 17.62, category: 'Household', tags: [] },
    ],
  },
  {
    id: '092',
    merchant: 'MARS_MART',
    merchantId: 'mrc-002',
    date: '2024.10.10',
    total: 82.10,
    itemCount: 8,
    status: 'OK',
    items: [],
  },
  {
    id: '091',
    merchant: 'TRADER_JOE_STN',
    merchantId: 'mrc-003',
    date: '2024.10.05',
    total: 67.45,
    itemCount: 6,
    status: 'OK',
    items: [],
  },
  {
    id: '090',
    merchant: 'COSTCO_SECTOR',
    merchantId: 'mrc-004',
    date: '2024.09.28',
    total: 214.80,
    itemCount: 15,
    status: 'PND',
    items: [],
  },
  {
    id: '089',
    merchant: 'ALDI_OUTPOST',
    merchantId: 'mrc-005',
    date: '2024.09.22',
    total: 48.30,
    itemCount: 5,
    status: 'OK',
    items: [],
  },
  {
    id: '088',
    merchant: 'INSTACART_OPS',
    merchantId: 'mrc-006',
    date: '2024.09.15',
    total: 312.60,
    itemCount: 20,
    status: 'ERR',
    items: [],
  },
  {
    id: '087',
    merchant: 'WHOLE_FOODS_7',
    merchantId: 'mrc-007',
    date: '2024.09.08',
    total: 98.20,
    itemCount: 10,
    status: 'OK',
    items: [],
  },
];

export const items: Item[] = [
  {
    id: 'plasma-conduit',
    name: 'Bananas',
    codename: 'PLASMA_CONDUIT',
    emoji: '🍌',
    category: 'produce',
    lastPrice: 0.89,
    lastDate: '10.12',
    lowestPrice: 0.72,
    lowestDate: '08.20',
    freqSource: 'TRADER_JOES_STN',
    unit: 'kCr / kg',
    delta: -18,
    deltaDir: 'down',
    alert: 'drop',
    tags: ['ORGANIC', 'PRODUCE'],
    priceHistory: [
      { month: 'JUL', price: 0.95 },
      { month: 'AUG', price: 0.72 },
      { month: 'SEP', price: 0.82 },
      { month: 'OCT', price: 0.89 },
    ],
  },
  {
    id: 'dark-brew-16',
    name: 'Kombucha 16oz',
    codename: 'DARK_BREW_16',
    emoji: '🍵',
    category: 'bev',
    lastPrice: 5.49,
    lastDate: '10.14',
    lowestPrice: 3.99,
    lowestDate: '08.15',
    freqSource: 'WHOLE_FOODS_7',
    unit: 'kCr / unit',
    delta: 38,
    deltaDir: 'up',
    alert: 'spike',
    tags: ['SPIKE', 'BEVERAGES'],
    priceHistory: [
      { month: 'JUL', price: 3.99 },
      { month: 'AUG', price: 3.99 },
      { month: 'SEP', price: 4.29 },
      { month: 'OCT', price: 5.49 },
    ],
  },
  {
    id: 'protein-matrix-a',
    name: 'Chicken Breast 1lb',
    codename: 'PROTEIN_MATRIX_A',
    emoji: '🍗',
    category: 'protein',
    lastPrice: 9.20,
    lastDate: '10.10',
    lowestPrice: 8.50,
    lowestDate: '09.01',
    freqSource: 'MARS_MART',
    unit: 'kCr / lb',
    delta: -11,
    deltaDir: 'down',
    alert: 'drop',
    tags: ['DEAL', 'PROTEIN'],
    priceHistory: [
      { month: 'JUL', price: 10.20 },
      { month: 'AUG', price: 9.80 },
      { month: 'SEP', price: 8.50 },
      { month: 'OCT', price: 9.20 },
    ],
  },
  {
    id: 'organic-fuel-cells',
    name: 'Free Range Eggs 12pk',
    codename: 'ORGANIC_FUEL_CELLS',
    emoji: '🥚',
    category: 'dairy',
    lastPrice: 4.50,
    lastDate: '10.08',
    lowestPrice: 4.20,
    lowestDate: '07.15',
    freqSource: 'COSTCO_SECTOR',
    unit: 'kCr / dz',
    delta: 0,
    deltaDir: 'flat',
    alert: null,
    tags: ['ORGANIC', 'DAIRY'],
    priceHistory: [
      { month: 'JUL', price: 4.20 },
      { month: 'AUG', price: 4.50 },
      { month: 'SEP', price: 4.50 },
      { month: 'OCT', price: 4.50 },
    ],
  },
  {
    id: 'lube-org-500ml',
    name: 'Olive Oil 500ml',
    codename: 'LUBE_ORG_500ML',
    emoji: '🫒',
    category: 'pantry',
    lastPrice: 11.99,
    lastDate: '10.14',
    lowestPrice: 10.50,
    lowestDate: '06.20',
    freqSource: 'WHOLE_FOODS_7',
    unit: 'kCr / btl',
    delta: 9,
    deltaDir: 'up',
    alert: 'watch',
    tags: ['WATCH', 'PANTRY'],
    priceHistory: [
      { month: 'JUL', price: 10.99 },
      { month: 'AUG', price: 11.29 },
      { month: 'SEP', price: 11.49 },
      { month: 'OCT', price: 11.99 },
    ],
  },
  {
    id: 'hydro-fluid-org',
    name: 'Whole Milk 1gal',
    codename: 'HYDRO_FLUID_ORG',
    emoji: '🥛',
    category: 'dairy',
    lastPrice: 3.49,
    lastDate: '10.12',
    lowestPrice: 3.29,
    lowestDate: '08.10',
    freqSource: 'TRADER_JOES_STN',
    unit: 'kCr / gal',
    delta: -2,
    deltaDir: 'down',
    alert: null,
    tags: ['ORGANIC', 'DAIRY'],
    priceHistory: [
      { month: 'JUL', price: 3.59 },
      { month: 'AUG', price: 3.29 },
      { month: 'SEP', price: 3.45 },
      { month: 'OCT', price: 3.49 },
    ],
  },
  {
    id: 'carbo-slab-sdg',
    name: 'Sourdough Loaf',
    codename: 'CARBO_SLAB_SDG',
    emoji: '🍞',
    category: 'pantry',
    lastPrice: 7.99,
    lastDate: '10.14',
    lowestPrice: 6.99,
    lowestDate: '07.01',
    freqSource: 'WHOLE_FOODS_7',
    unit: 'kCr / loaf',
    delta: 0.5,
    deltaDir: 'flat',
    alert: null,
    tags: ['BAKERY', 'PANTRY'],
    priceHistory: [
      { month: 'JUL', price: 6.99 },
      { month: 'AUG', price: 7.49 },
      { month: 'SEP', price: 7.79 },
      { month: 'OCT', price: 7.99 },
    ],
  },
  {
    id: 'chloro-pack-5oz',
    name: 'Baby Spinach 5oz',
    codename: 'CHLORO_PACK_5OZ',
    emoji: '🥬',
    category: 'produce',
    lastPrice: 3.99,
    lastDate: '10.14',
    lowestPrice: 3.49,
    lowestDate: '09.05',
    freqSource: 'WHOLE_FOODS_7',
    unit: 'kCr / bag',
    delta: -5,
    deltaDir: 'down',
    alert: null,
    tags: ['ORGANIC', 'PRODUCE'],
    priceHistory: [
      { month: 'JUL', price: 4.29 },
      { month: 'AUG', price: 4.19 },
      { month: 'SEP', price: 3.49 },
      { month: 'OCT', price: 3.99 },
    ],
  },
  {
    id: 'hull-cleaner-lg',
    name: 'Laundry Detergent',
    codename: 'HULL_CLEANER_LRG',
    emoji: '🧴',
    category: 'house',
    lastPrice: 17.62,
    lastDate: '10.08',
    lowestPrice: 14.99,
    lowestDate: '06.15',
    freqSource: 'COSTCO_SECTOR',
    unit: 'kCr / unit',
    delta: 6,
    deltaDir: 'up',
    alert: 'watch',
    tags: ['WATCH', 'HOUSEHOLD'],
    priceHistory: [
      { month: 'JUL', price: 15.99 },
      { month: 'AUG', price: 16.49 },
      { month: 'SEP', price: 16.99 },
      { month: 'OCT', price: 17.62 },
    ],
  },
  {
    id: 'solid-block-chd',
    name: 'Cheddar Cheese 8oz',
    codename: 'SOLID_BLOCK_CHD',
    emoji: '🧀',
    category: 'dairy',
    lastPrice: 3.50,
    lastDate: '10.14',
    lowestPrice: 2.99,
    lowestDate: '08.25',
    freqSource: 'WHOLE_FOODS_7',
    unit: 'kCr / block',
    delta: -12,
    deltaDir: 'down',
    alert: null,
    tags: ['SALE', 'DAIRY'],
    priceHistory: [
      { month: 'JUL', price: 3.99 },
      { month: 'AUG', price: 2.99 },
      { month: 'SEP', price: 3.79 },
      { month: 'OCT', price: 3.50 },
    ],
  },
  {
    id: 'carbo-strands-1lb',
    name: 'Pasta Spaghetti 1lb',
    codename: 'CARBO_STRANDS_1LB',
    emoji: '🍝',
    category: 'pantry',
    lastPrice: 1.79,
    lastDate: '10.05',
    lowestPrice: 1.49,
    lowestDate: '07.20',
    freqSource: 'ALDI_OUTPOST',
    unit: 'kCr / unit',
    delta: 1.1,
    deltaDir: 'flat',
    alert: null,
    tags: ['PANTRY'],
    priceHistory: [
      { month: 'JUL', price: 1.49 },
      { month: 'AUG', price: 1.69 },
      { month: 'SEP', price: 1.75 },
      { month: 'OCT', price: 1.79 },
    ],
  },
  {
    id: 'cultured-gel-32oz',
    name: 'Greek Yogurt 32oz',
    codename: 'CULTURED_GEL_32OZ',
    emoji: '🫙',
    category: 'dairy',
    lastPrice: 6.49,
    lastDate: '10.12',
    lowestPrice: 5.99,
    lowestDate: '07.10',
    freqSource: 'TRADER_JOES_STN',
    unit: 'kCr / tub',
    delta: 3,
    deltaDir: 'up',
    alert: null,
    tags: ['DAIRY'],
    priceHistory: [
      { month: 'JUL', price: 5.99 },
      { month: 'AUG', price: 6.29 },
      { month: 'SEP', price: 6.39 },
      { month: 'OCT', price: 6.49 },
    ],
  },
];

export const manifests: Manifest[] = [
  {
    id: 'mft-042',
    title: 'WEEK_42_REUP',
    type: 'WEEKLY',
    status: 'active',
    estTotal: 312,
    confidence: '±7%',
    lastModified: '14:31 TODAY',
    checkedCount: 3,
    items: [
      { id: 'mi-001', name: 'Organic Fuel Cells (Eggs)', checked: true, prevPrice: 4.50, location: null, unknown: false },
      { id: 'mi-002', name: 'Hydro-Packs (Water 24pk)', checked: false, prevPrice: 6.99, location: null, unknown: false },
      { id: 'mi-003', name: 'Protein Matrix (Chicken)', checked: false, prevPrice: 18.40, location: 'MARS_MART', unknown: false },
      { id: 'mi-004', name: 'Plasma Conduit (Bananas)', checked: false, prevPrice: 0.89, location: 'TJ_STN', unknown: false },
      { id: 'mi-005', name: 'Dark Matter Spice', checked: false, prevPrice: null, location: null, unknown: true },
      { id: 'mi-006', name: 'Carbon Fiber Rolls (TP)', checked: false, prevPrice: 22.00, location: 'COSTCO', unknown: false },
      { id: 'mi-007', name: 'Synth-Brew (Coffee)', checked: true, prevPrice: 14.99, location: 'TJ_STN', unknown: false },
    ],
    crew: [
      { initials: 'CP', name: 'CAPT_PROVISIONS', role: 'SECTOR_7 // HQ', color: '#4A3828', badge: 'COMMANDER' },
      { initials: 'JD', name: 'J.DAVIDSON', role: 'GRID_B7 // FIELD', color: '#2A3848', badge: 'OPERATOR' },
      { initials: 'AL', name: 'A.LOPEZ', role: 'GRID_B7 // FIELD', color: '#3A2848', badge: 'OPERATOR' },
    ],
  },
  {
    id: 'mft-041',
    title: 'BULK_COSTCO_RUN',
    type: 'BULK',
    status: 'active',
    estTotal: 265,
    confidence: '±4%',
    lastModified: '12:08 TODAY',
    checkedCount: 7,
    items: [
      { id: 'mi-008', name: 'Olive Oil 1L', checked: true, prevPrice: 19.99, location: 'COSTCO', unknown: false },
      { id: 'mi-009', name: 'Chicken Breast 5lb', checked: true, prevPrice: 38.50, location: 'COSTCO', unknown: false },
      { id: 'mi-010', name: 'Toilet Paper 30pk', checked: true, prevPrice: 22.00, location: 'COSTCO', unknown: false },
      { id: 'mi-011', name: 'Detergent Bulk', checked: false, prevPrice: 17.62, location: 'COSTCO', unknown: false },
      { id: 'mi-012', name: 'Frozen Berries 3pk', checked: false, prevPrice: 12.99, location: null, unknown: false },
    ],
    crew: [
      { initials: 'CP', name: 'CAPT_PROVISIONS', role: 'SECTOR_7 // HQ', color: '#4A3828', badge: 'COMMANDER' },
      { initials: 'JD', name: 'J.DAVIDSON', role: 'GRID_B7 // FIELD', color: '#2A3848', badge: 'OPERATOR' },
    ],
  },
  {
    id: 'mft-040',
    title: 'MONTHLY_PROVISIONS',
    type: 'MONTHLY',
    status: 'active',
    estTotal: 406,
    confidence: '±12%',
    lastModified: '10.13 YESTERDAY',
    checkedCount: 1,
    items: [
      { id: 'mi-013', name: 'Monthly Essentials Pack', checked: true, prevPrice: null, location: null, unknown: false },
      { id: 'mi-014', name: 'Spice Rack Refill', checked: false, prevPrice: null, location: null, unknown: true },
    ],
    crew: [
      { initials: 'CP', name: 'CAPT_PROVISIONS', role: 'SECTOR_7 // HQ', color: '#4A3828', badge: 'COMMANDER' },
    ],
  },
  {
    id: 'mft-draft-03',
    title: 'PHARMACY_RUN',
    type: 'HEALTH',
    status: 'draft',
    estTotal: 45,
    confidence: 'ROUGH',
    lastModified: 'CREATED: 10.12',
    checkedCount: 0,
    items: [
      { id: 'mi-015', name: 'Vitamins D3', checked: false, prevPrice: null, location: null, unknown: true },
      { id: 'mi-016', name: 'Bandages Pack', checked: false, prevPrice: null, location: null, unknown: true },
    ],
    crew: [
      { initials: 'CP', name: 'CAPT_PROVISIONS', role: 'SECTOR_7 // HQ', color: '#4A3828', badge: 'COMMANDER' },
    ],
  },
  {
    id: 'mft-draft-04',
    title: 'HOLIDAY_STOCK',
    type: 'SEASONAL',
    status: 'draft',
    estTotal: 180,
    confidence: 'ROUGH',
    lastModified: 'CREATED: 10.11',
    checkedCount: 0,
    items: [],
    crew: [
      { initials: 'CP', name: 'CAPT_PROVISIONS', role: 'SECTOR_7 // HQ', color: '#4A3828', badge: 'COMMANDER' },
      { initials: 'AL', name: 'A.LOPEZ', role: 'GRID_B7 // FIELD', color: '#3A2848', badge: 'OPERATOR' },
    ],
  },
  {
    id: 'mft-039',
    title: 'WEEK_41_REUP',
    type: 'WEEKLY',
    status: 'done',
    estTotal: 298,
    confidence: '-2.3% vs EST',
    lastModified: 'CLOSED: 10.07',
    checkedCount: 14,
    items: [],
    crew: [
      { initials: 'CP', name: 'CAPT_PROVISIONS', role: 'SECTOR_7 // HQ', color: '#4A3828', badge: 'COMMANDER' },
      { initials: 'JD', name: 'J.DAVIDSON', role: 'GRID_B7 // FIELD', color: '#2A3848', badge: 'OPERATOR' },
    ],
  },
  {
    id: 'mft-031',
    title: 'SEP_MONTHLY_STOCK',
    type: 'MONTHLY',
    status: 'archived',
    estTotal: 374,
    confidence: 'FINAL kCr',
    lastModified: 'ARCHIVED: 09.30',
    checkedCount: 0,
    items: [],
    crew: [],
  },
];

export const analytics: Analytics = {
  period: 'OCT 2024',
  totalSpend: 4285,
  budget: 5000,
  kpis: [
    { label: 'TOTAL_OPS', value: '4,285', delta: '▲ +8.3% vs last', deltaType: 'neg' },
    { label: 'AVG_SORTIE', value: '238', delta: '▼ -3.1% vs last', deltaType: 'pos' },
    { label: 'MISSIONS', value: '18', delta: '► +2 vs last', deltaType: 'warn' },
  ],
  categorySpend: [
    { name: 'Provisions (Grocery)', emoji: '🥦', amount: 2657, pct: 62, color: 'var(--green)' },
    { name: 'Hull Supplies (House)', emoji: '🏠', amount: 771, pct: 18, color: 'var(--blue)' },
    { name: 'Tech Components', emoji: '⚗️', amount: 514, pct: 12, color: 'var(--amber)' },
    { name: 'Emergency Rations', emoji: '🚨', amount: 343, pct: 8, color: 'var(--red)' },
  ],
  merchants: [
    { name: 'COSTCO_SECTOR', visits: 5, amount: 1241, color: 'var(--amber)' },
    { name: 'WHOLE_FOODS_7', visits: 4, amount: 892 },
    { name: 'TRADER_JOE_STN', visits: 4, amount: 764 },
    { name: 'MARS_MART', visits: 3, amount: 523 },
    { name: 'INSTACART_OPS', visits: 2, amount: 865, color: 'var(--red)' },
  ],
  insights: [
    {
      title: 'OVER-RELIANCE DETECTED',
      body: 'INSTACART_OPS accounts for 20.2% of spend but only 11% of item volume — delivery surcharges inflating cost.',
      badge: 'COST_LEAK',
      badgeType: 'red',
      icon: '⚠️',
      borderColor: 'rgba(166,68,68,0.35)',
      iconBg: 'rgba(166,68,68,0.12)',
    },
    {
      title: 'PRICE_DROP WINDOW',
      body: 'PLASMA_CONDUIT (Bananas) historically 18% cheaper in weeks 43–46. Stock recommended.',
      badge: 'OPPORTUNITY',
      badgeType: 'green',
      icon: '📉',
      borderColor: 'rgba(120,168,144,0.3)',
      iconBg: 'rgba(120,168,144,0.1)',
    },
    {
      title: 'INFLATION_SIGNAL: DAIRY',
      body: 'Dairy sector up +5.8% over 60-day window. Consider bulk procurement before cycle-end.',
      badge: 'MONITOR',
      badgeType: 'amber',
      icon: '📡',
      borderColor: 'rgba(217,140,69,0.3)',
      iconBg: 'rgba(217,140,69,0.1)',
    },
  ],
};

export const userProfile: UserProfile = {
  callsign: 'CAPT_PROV',
  rank: 'CAPTAIN_PROVISIONS',
  email: 'capt.provisions@conduit.net',
  level: 4,
  xp: 7240,
  xpNext: 10000,
  missions: 18,
  itemsTracked: 142,
  variance: '-4.2%',
};
