config:
  edition: 3
streams:
  user_scoped:
    auto_subscribe: true
    queries:
      - SELECT * FROM categories WHERE user_id = auth.user_id()
      - SELECT * FROM items WHERE user_id = auth.user_id()
      - SELECT * FROM manifest_crew WHERE manifest_id IN (SELECT id FROM manifests WHERE user_id = auth.user_id())
      - SELECT * FROM manifest_crew WHERE user_id = auth.user_id()
      - SELECT * FROM manifest_items WHERE manifest_id IN (SELECT id FROM manifests WHERE user_id = auth.user_id())
      - SELECT * FROM manifest_items WHERE manifest_id IN (SELECT manifest_id FROM manifest_crew WHERE user_id = auth.user_id())
      - SELECT * FROM manifests WHERE user_id = auth.user_id()
      - SELECT * FROM manifests WHERE id IN (SELECT manifest_id FROM manifest_crew WHERE user_id = auth.user_id())
      - SELECT * FROM merchants WHERE user_id = auth.user_id()
      - SELECT * FROM receipt_items WHERE receipt_id IN (SELECT id FROM receipts WHERE user_id = auth.user_id()) 
      - SELECT * FROM receipts WHERE user_id = auth.user_id()
      - SELECT * FROM tags WHERE user_id = auth.user_id()
      - SELECT * FROM merchant_aisles WHERE user_id = auth.user_id()
      - SELECT * FROM merchant_item_rules WHERE user_id = auth.user_id()
      - SELECT * FROM "user" WHERE id = auth.user_id()
      - SELECT * FROM "user" WHERE id IN (SELECT user_id_b FROM user_crew WHERE user_id_a = auth.user_id())
      - SELECT * FROM "user" WHERE id IN (SELECT user_id_a FROM user_crew WHERE user_id_b = auth.user_id())
      - SELECT * FROM "user" WHERE id IN (SELECT user_id FROM manifest_crew WHERE manifest_id IN (SELECT id FROM manifests WHERE user_id = auth.user_id()))
      - SELECT * FROM "user" WHERE id IN (SELECT user_id FROM manifest_crew WHERE manifest_id IN (SELECT manifest_id FROM manifest_crew WHERE user_id = auth.user_id()))
      - SELECT * FROM user_crew WHERE user_id_a = auth.user_id() OR user_id_b = auth.user_id()
      - SELECT * FROM processing_rules WHERE user_id = auth.user_id()
