config:
  edition: 3
streams:
  user_scoped:
    auto_subscribe: true
    queries:
      - SELECT * FROM categories WHERE user_id = auth.user_id()
      - SELECT * FROM items WHERE user_id = auth.user_id()
      - SELECT * FROM manifest_crew WHERE manifest_id IN (SELECT id FROM manifests WHERE user_id = auth.user_id())
      - SELECT * FROM manifest_items WHERE manifest_id IN (SELECT id FROM manifests WHERE user_id = auth.user_id())
      - SELECT * FROM manifests WHERE user_id = auth.user_id()
      - SELECT * FROM merchants WHERE user_id = auth.user_id()
      - SELECT * FROM receipt_items WHERE receipt_id IN (SELECT id FROM receipts WHERE user_id = auth.user_id()) 
      - SELECT * FROM receipts WHERE user_id = auth.user_id()
      - SELECT * FROM tags WHERE user_id = auth.user_id()
      - SELECT * FROM users WHERE id = auth.user_id()
